[package]
name = "task-maker-test-sandbox"
version = "0.5.1"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
tabox = "1"
serde = "1.0"
serde_json = "1.0"
task-maker-exec = { path = "../../task-maker-exec" }
env_logger = "0.6"